delete commas in names, preset the „wert“ column for all abos, total …
orbiting/republik-backend pull request #40
Opened 2018-01-05 12:10 UTC by pozylon

@clarajeanne 

> A comma in the name field leads to wrong representation. Example: pledge-id afbe7944-2aa8
The ABO_total row should be the product of ABO_wert and # ABO, same for all Product_total fields
ABO_wert should always be 240, even if there is no ABO in this pledge, same for all Product_wert fields
Row ABO_REDUCED total should show the price that was paid, not 240

- I just lazily remove commas now
- Total is now a product
- ABO_* columns are specific for their corresponding pledge option and the donation is on the payment level, donation can/should therefore only influence payment total columns as it could be potentially dangerous to reduce the ABO_REDUCED total by the global donation in the future.

2018-01-06 00:12 UTC, patte requested changes

2018-01-06 00:12 UTC, patte commented on modules/crowdfundings/graphql/resolvers/_queries/paymentsCSV.js
> +      lastName: result.lastName.replace(/,/gi, ''),
this should not be necessary, `dsvFormat` should handle this cases. Also, this export is `;` separated so `,` should not be a problem. @clarajeanne please check your import/open setting in libreoffice to only separate by `;` for this file.
Should be removed.

2018-01-06 00:12 UTC, patte commented on modules/crowdfundings/graphql/resolvers/_queries/paymentsCSV.js
> +      ...(convertPackage('ABO_BENEFACTOR', benefactorAbos, 100000)),
price is persisted and should be loaded from the `pledgeOptions`.

2018-01-06 00:13 UTC, patte commented
@pozylon can you create a export an your machine, send it to @clarajeanne so that she can approve the changes please?

2018-01-08 14:57 UTC, pozylon commented
Got rid of the magic numbers in "wert" but they are still kind of "magic" because of different crowdfundingId's. 

The code in paymentsCSV is republik-oppinionated anyhow so we should not touch this anymore now and export on the base of immutable log entries in the future.

2018-01-08 21:43 UTC, patte commented
@clarajeanne what's the status here?

2018-01-09 12:21 UTC, clarajeanne approved these changes
Awesome! Thx

2018-01-09 13:46 UTC, patte approved these changes

2018-01-09 13:47 UTC, merged